name: QA Master Project CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pytest pytest-playwright selenium flask flask-sqlalchemy requests webdriver-manager
          playwright install --with-deps chromium
      - name: Run Tests
        run: |
          python app.py &
          sleep 10
          python -m pytest tests/ -v